### ISSUE TITLE
Channel and Video meta attributes

### ISSUE THREAD

**Issue by richardARPANET** [VeemsHQ/veems#107]
**Channel Tags**

- [x] Create a hardcoded list of suggested tags. 
- [x] Allow the user to assign any tags to their Channel. Maximum of 3.
- [x] /channel/customization/ form with React
- [x] E2E test (Channel ops and Video upload ops)

**Channel Language**

- [x] Select from a drop-down the 'primary language' for the Channel. 

**Video Tags**

- [x] Allow the user to assign any tags to their Video. 
- [x] Maximum of 5 tags
- [x] Same form input control as Channel tags form
- [x] Video tags input fails to render is video has no tags
