### ISSUE TITLE
Playlist API for Videos

### ISSUE THREAD

**Issue by richardARPANET** [VeemsHQ/veems#5]
Example here https://www.jwplayer.com/developers/web-player-demos/mpeg-dash/

Each Video should also have a playlist endpoint.

Return all the various transcodes along with the URL for the video.

Non-CDN URL for the video initially. Follow up task will be done to change to CDN-backed URL.

Add playlist API URL to the Get Video resp.

### TODO

- [x] Add function to split single whole video file into many segments (.ts files), one playlist per rendition
- [x] Store rendition data on object storage server
- [x] Rendition, Add DB records, link to Video record
- [x] Master playlist
- [x] Add Get Playlist for Video API Endpoint

-----

branch: playlist

https://superuser.com/questions/1106343/determine-video-bitrate-using-ffmpeg/1111039
https://www.nginx.com/resources/videos/nginx-for-commercial-quality-streaming-services/
https://docs.unified-streaming.com/best-practice/vod.html
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/on-demand-streaming-video.html

https://hlsbook.net/segmenting-video-with-ffmpeg-part-2/
https://developer.apple.com/documentation/http_live_streaming/example_playlists_for_http_live_streaming/creating_a_master_playlist
